import json
import os
import sys

import firebase_admin
import lyricsgenius
from dotenv import load_dotenv
from youtube_title_parse import get_artist_title

from db import database as db, YoutubeDownload
from listener.IBMWatson import SentimentAnalysis

load_dotenv()

token = os.environ['GENIUS_TOKEN']
genius = lyricsgenius.Genius(token)


def generate_file_name(filename):
    """
    fn to take a youtube-dl mp3 file, and convert to title_author
    :param filename: filename from youtube-dl mp3
    :return: artist, title
    """
    filename = filename.replace('_', ' ')
    filename = filename.replace('.mp3', '')
    filename = filename.replace('.', '')
    filename = filename.replace("'", '')
    artist, title = get_artist_title(filename)
    return artist, title


def collectSongData(lyrics):

    # FUNCTION TO GET ONLY LYRICS
    helper_string = ''
    add_to_substring = False
    for index, char in enumerate(lyrics):
        if char == '[':
            add_to_substring = True
        if add_to_substring:
            helper_string += char
        if char == ']':
            lyrics = lyrics.replace(helper_string, '')
            helper_string = ''
            add_to_substring = False

    watson = SentimentAnalysis(lyrics)
    return lyrics, watson


def generate_corpus(url='https://www.youtube.com/watch?v=fHR1CZ9x61E&list=PLIp9ZTeVjWUXaM10x2DTlNV-jGk6lskhE&ab_channel=YoungMoneyEntertainment'):
    """
    Given a youtube playlist and directory of filenames, constructs corpus of songs,lyrics, and sentiment
    :param directory: path to directory of filenames generated by youtube-dl
    :return: None

    https://www.youtube.com/playlist?list=PLJD57x-QI7Q3Oy09MsXwM055nKu7b2B8A
    """

    YoutubeDownload.youtube_downloader(url)

    _, _, filenames = next(os.walk('./downloadedsongs'))


    try:
        songs = []
        for file in filenames:
            artist, title = generate_file_name(file)
            lyrics, watson = GetSongLyricsAndSentiment(title, artist)
            songs.append([title, artist, lyrics, watson, file])

        # write to corpus
        db.write(songs)
        return True

    except Exception as e:
        print(e, file=sys.stderr)


def GetSongLyricsAndSentiment(song_name, artist_name):
    try:
        # Search song name and artist for lyrics on genius
        song = genius.search_song(song_name, artist_name)
        # Fetch the watson response
        lyrics, watson = collectSongData(song.lyrics)
        return lyrics, watson

    except AttributeError as e:
        print(e)
        pass
